### ISSUE TITLE
CommonJS compatibility

### ISSUE THREAD

**Issue by Dolu89** [synonymdev/slashtags#79]
Hi

I can't use slashtags packages in my Zerologin project as is. Zerologin is developed using AdonisJS framework version 5 which uses CommonJS (next version 6 should be ESM first)
Is there a possibility to add CommonJS compilation next to ESM?

Thanks

**Comment by rbndg** [comment]
@Nazeh how much effort would it be to have cmjs version of sdk?

**Comment by Nazeh** [comment]
@rbndg We had a build pipeline for ES + CJS but it was seriously hurting the project's readability.

@Dolu89 Are the following options impossible for your project?
```js
// Inside an async function:
async function app () {
  const sdk = await import('@synonymdev/slashtags-sdk');
}
app()
```

```js
// Or in top level of foo.cjs
import('@synonymdev/slashtags-sdk').then((sdk) => {
  // do stuff.
})
```

**Comment by Dolu89** [comment]
No unfortunately dynamic import doesn't work
I still have the same error

```sh
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/dolu/Projects/zero-login/node_modules/@synonymdev/slashtags-sdk/index.js from /Users/dolu/Projects/zero-login/start/slashtags.ts not supported.
    Instead change the require of index.js in /Users/dolu/Projects/zero-login/start/slashtags.ts to a dynamic import() which is available in all CommonJS modules.
```

**Comment by Nazeh** [comment]
@Dolu89 it definitely does, but I assume from the error, that your Typescript builds this:
```ts
import('@synonymdev/slashtags-sdk').then(({SDK}) =>{
  console.log(SDK)
})
```
Into this:
```js
// ...
Promise.resolve().then(() => __importStar(require('@synonymdev/slashtags-sdk'))).then(({ SDK }) => {
    console.log(SDK);
});
```
Instead of this:
```js
import('@synonymdev/slashtags-sdk').then(({ SDK }) => {
    console.log(SDK);
});
```
That is because your `"module"` value in `adonis-preset-ts/tsconfig` is `"commonjs"

Not sure how to solve this for you without you moving to `"module": "esnext"` or something similar, but I recognize that you will have to fix few things afterwards (I tried in your `zerologin` repo).

Alternatively, I will have to bundle the SDK for commonjs using `esbuild`, but I won't be testing it afterward with, so if anything breaks in the bundled version (a lot breaks in bundling) then it will go untested.
